### PR TITLE
Make changing PluginSettings from build scripts possible

### PR DESCRIPTION
**Pull request by JashanChittesh**
This is a quick fix for enabling changes to PluginSettings from build scripts. The issue was that Data is a struct only accessible via a static getter; so there was no way to change the values from code, which is a requirement in our project because we have multiple games in the same project and simply use different build scripts for the different games.

This does not fix the issue that we need to duplicate the code to load PluginSettings from the resources. It would be preferable to get the PluginSettings singleton-style instead of using it as just a wrapper for data; so instead of writing PluginSettings.data, it would be PluginSettings.Instance.data. That way, the PluginSettings asset could be loaded and marked easily as dirty for the assets database.

This mostly fixes https://github.com/modio/UnityPlugin/issues/21

### CODE REVIEW

**Comment by Melodatron** [comment]
Hi @JashanChittesh, I understand the difficulty with the current setup per your needs, and see that your solution enables some good functionality.
I initially made the decision to use a struct and structure you see in an effort to create "self-documenting" code such that I wished to indicate that the plugin expects these values to remain constant over the lifetime of a program.
As an alternative to your solution, would it be useful to allow you to easily alter the location of the PluginSettings prior to the data being loaded, such that you could select which settings to use via build scripts?

**Comment by Melodatron** [comment]
Would a solution such as this fulfill your needs?
```java
/// <summary>Sets the values of the Plugin Settings.</summary>
public static PluginSettings SetGlobalValues(PluginSettings.Data data)
{
    string assetPath = "Assets/Resources/" + PluginSettings.FILE_PATH + ".asset";
    PluginSettings settings = ScriptableObject.CreateInstance<PluginSettings>();

    if(!UnityEditor.AssetDatabase.IsValidFolder("Assets/Resources"))
    {
        UnityEditor.AssetDatabase.CreateFolder("Assets", "Resources");
    }

    settings.m_data = data;

    UnityEditor.AssetDatabase.CreateAsset(settings, assetPath);
    UnityEditor.AssetDatabase.SaveAssets();
    UnityEditor.AssetDatabase.Refresh();

    return settings;
}

/// <summary>Copies a Plugin Settings' values into the main asset.</summary>
public static PluginSettings SetAssetAsGlobal(string assetPath)
{
    PluginSettings valuesToCopy = UnityEditor.AssetDatabase.LoadAssetAtPath(assetPath);
    if(valuesToCopy == null)
    {
        Debug.LogError("[mod.io] PluginSettings at " + assetPath + " could not be found and"
                       + " thus the globally used PluginSettings asset was unchanged.");
        return null;
    }

    return PluginSettings.SetGlobalValues(valuesToCopy.data);
}
```

**Comment by JashanChittesh** [comment]
I believe SetGlobalValues would probably work for me. So I'd get the data, override it as needed, and store it using SetGlobalValues.

This could probably be wrapped in #if UNITY_EDITOR, which would make it clear that data cannot be changed during runtime.

**Comment by Melodatron** [comment]
As discussed, I've implemented the above solution, so let me know if there is any further functionality required.

**Pull request closed without merging**
