### PR TITLE
Improve examples for UPM

### PR DESCRIPTION
**Pull request by MeikelLP**
* Unity does not import folders suffixed with `~`. That's why all the .meta files (for the examples) are removed.
* UPM supports defining samples which can then be manually imported via the package manager UI (for reference: https://github.com/Unity-Technologies/ScriptableRenderPipeline/blob/master/com.unity.render-pipelines.high-definition/package.json)

I recommend having a seperate UPM branch for the upm support: https://openupm.com/docs/adding-upm-package.html

### CODE REVIEW

**Comment by Melodatron** [comment]
@MeikelLP Thanks, this is a great suggestion!

**Comment by MeikelLP** [comment]
I saw you moved `Samples~` -> `Samples`. What's the reason behind that?

**Comment by Melodatron** [comment]
I'm currently in the process of creating a UPM branch, for which the folder is named  `Samples~`, but I need the folder without the `~` in the main repo so that I can continue to work on it easily and export it with the UnityPackage.
Sorry for the confusion!

**Comment by Melodatron** [comment]
@MeikelLP Just finished making the repo fully UPM compatible. It turns out creating a UPM branch was far more difficult and error-prone than making the whole repo UPM supported.
Thanks again for the suggestion.

**Comment by MeikelLP** [comment]
Thank you for your good work man!

**Pull request merged**
